apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpf
  labels:
    app: bpf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bpf
  template:
    metadata:
      labels:
        app: bpf
        build-time: "<BUILD_TIME>"
    spec:
      containers:
        - name: bpf
          resources:
            limits:
              memory: "256Mi"
          image: bpf-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
                - IPC_LOCK
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io